apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsonnodeapp
  labels:
    app: jsonnodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jsonnodeapp
  template:
    metadata:
      labels:
        app: jsonnodeapp
    spec:
      containers:
      - name: jsonnodeapp
        image: yogeshtembe/jsonnodeapp
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: jsonnodeapp-service
spec:
  selector:
    app: jsonnodeapp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
    nodePort: 30031
