sudo: required
services:
  - docker

before_install: 
  - docker build -t cparkhi16/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true cparkhi16/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-603653448533"
  bucket_path: "docker-react"
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY # this is IAM User (docker-react)'s access key and secret access who has AdministrativeAccessForAWSElasticBeanStalk Permission attached to it (see mailed notes)
    secret_access_key: "$AWS_SECRET_KEY"
