sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t cparkhi16/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cparkhi16/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1" # region of env
  app: "docker-react" #application name 
  env: "Dockerreact-env" # env name 
  bucket_name: "elasticbeanstalk-us-east-1-603653448533"
  bucket_path: "docker-react" # in s3 
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY # this is IAM User (docker-react)'s access key and secret access who has AdministrativeAccessForAWSElasticBeanStalk Permission attached to it (see mailed notes)
  secret_access_key: $AWS_SECRET_KEY





































