apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache2dep
  labels:
    app: apache2dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache2dep
  template:
    metadata:
      labels:
        app: apache2dep
    spec:
      containers:
      - name: apache2
        image: yogeshtembe/apacheapp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache2serv
spec:
  selector:
    app: apache2dep
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 80
    nodePort: 30080
