apiVersion: networking.k8s.io/v1
# UPDATE API
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: 'nginx' # for configuring ingress-nginx controller
    nginx.ingress.kubernetes.io/use-regex: 'true'
    # ADD ANNOTATION
    nginx.ingress.kubernetes.io/rewrite-target: /$1 # this is required to remove /api once request is known to be routed to multi server pod we can remove it as there is no route starting with /api in multi server and already we have known to be routed to specific service
    # UPDATE ANNOTATION
    cert-manager.io/cluster-issuer: 'letsencrypt-prod' # let ingress service know which cluster issuer we are using for certs
    nginx.ingress.kubernetes.io/ssl-redirect: 'true' # compulsory use https connections from users
spec:
  tls: # for these hosts use tls connection by using cert from the given secret name which we will receive after certificate object is configured 
    - hosts:
        - k8s-multi.com
        - www.k8s-multi.com
      secretName: k8s-multi-com
  rules:
    - host: k8s-multi.com # handle connections for this host separately and www host separately
      http:
        paths:
          - path: /?(.*)
            # UPDATE PATH
            pathType: Prefix
            # ADD PATHTYPE
            backend:
              service:
                # UPDATE SERVICE FIELDS
                name: client-cluster-ip-service
                port:
                  number: 3000
          - path: /api/?(.*)
            # UPDATE PATH
            pathType: Prefix
            # ADD PATHTYPE
            backend:
              service:
                # UPDATE SERVICE FIELDS
                name: server-cluster-ip-service
                port:
                  number: 5000
    - host: www.k8s-multi.com
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: client-cluster-ip-service
                port:
                  number: 3000
          - path: /api/?(.*)
            pathType: Prefix
            backend:
              service:
                name: server-cluster-ip-service
                port:
                  number: 5000  
# see mailed info on installing ingress nginx setup for local env