apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongoserv-ingress
  namespace: test
spec:
  rules:
  - host: myapp.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mongoserv
            port: 
              number: 27017
