version: "3"
services:
  client:
    image: "cparkhi16/multi-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "cparkhi16/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "cparkhi16/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "cparkhi16/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"


# Each service is defined with an image property that specifies the Docker image to use for the service. The mem_limit property is used to limit the maximum amount of memory that each container can use.
# The hostname property sets the hostname for each service. This can be useful for container-to-container communication within the same network.
