apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache2dep  #anything
  namespace: test
  labels:
    app: apache2dep  #anything
spec:
  replicas: 1 #create 2 pods pod n replica
  selector:
    matchLabels:
      app: apache2dep  #attach elements from deploymemt having name nginx
  template:
    metadata:
      labels:
        app: apache2dep  #name same as nginx to associate it with nginx-dep deployment 
    spec:
      containers:
      - name: apache2
        image: cparkhi16/apache
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache2serve
spec:
  selector:
    app: apache2dep
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
      nodePort: 30002
