apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ${docker-registry}/my-app:1.0
        ports:
        - containerPort: 3000
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
        #value: blank , nextlines after secret
          valueFrom:
            secretKeyRef:
              name: mongo-sec
              key: user_name
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongo-sec
              key: psswd
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-sec
              key: user_name
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongo-sec
              key: psswd
        - name: ME_CONFIG_MONGODB_SERVER #create and apply config.yaml first
          valueFrom: 
            configMapKeyRef:
              name: mongo-config
              key: url 

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-sec
type: Opaque
data:
  user_name:  dXNlcm5hbWU=
  psswd: cGFzc3dvcmQ=

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongoexp-service
spec:
  selector:
    app: mongo-express
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000 #host port no range 30000 to 32767

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  url:  mongodb-service