apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqlapp
  labels:
    app: mysqlapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqlapp
  template:
    metadata:
      labels:
        app: mysqlapp
    spec:
      containers:
      - name: mysqlapp
        image: yogeshtembe/nodemysqlapp
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mysqlapp-service
spec:
  selector:
    app: mysqlapp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30030
