AWSTemplateFormatVersion: "2010-09-09"
Metadata:
  License: Apache-2.0
Description: 'AWS CloudFormation Template for the Ws'
Resources:
  WsCreateUser:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: "cfsfiles"
        S3Key: "lambda/test.zip"
      FunctionName: "CreateUser"
      Handler: "lambda_function.lambda_handler"
      Role: arn:aws:iam::845046348330:role/LambdaRole
      Runtime: "python3.8"
      Timeout: 29
      Environment:
        Variables:
          WS_REGION: 'us-east-2'