apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp
  labels:
    app: goapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: goapp
        image: cparkhi16/goapp
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: mygoservice
spec:
  selector:
    app: goapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 9000
      nodePort: 30008 #host port no range 30000 to 32767
