apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8.0.13
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mysqlsec
                key:  password
        - name:  MYSQL_USER
          valueFrom:
              secretKeyRef:
                name: mysqlsec
                key: username
        - name:  MYSQL_DATABASE
          valueFrom:
              secretKeyRef:
                name: mysqlsec
                key: dbname
        ports:
        - containerPort: 3306
          name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysqlserv
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
