apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoexp
  namespace: test2
  labels:
    app: mongoexp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoexp
  template:
    metadata:
      labels:
        app: mongoexp
    spec:
      containers:
      - name: mongoexp
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom: 
              secretKeyRef:
                name: mongosec
                key: username 
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom: 
              secretKeyRef:
                name: mongosec
                key: password
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom: 
              configMapKeyRef:
                name: expconfig
                key: url

