apiVersion: v1
kind: Service
metadata:
  name: mongoexpserve
  namespace: test2
spec:
  selector:
    app: mongoexp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30081
