apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresnodeapp
  labels:
    app: postgresnodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresnodeapp
  template:
    metadata:
      labels:
        app: postgresnodeapp
    spec:
      containers:
      - name: postgresnodeapp
        image: yogeshtembe/postgresnodeapp
        ports:
        - containerPort: 3000
        
---
apiVersion: v1
kind: Service
metadata:
  name: postgresnodeapp-service
spec:
  selector:
    app: postgresnodeapp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30033
